project_id = "xqepqbfsslfziivyfwie"

[functions.checkout]
verify_jwt = false

[functions.store-checkout]
verify_jwt = false

[functions.setup-card]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.create-setup-intent]
verify_jwt = true

[functions.stripe-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]
